import React from 'react';
import pt from 'prop-types';
// import { Montserrat, Open_Sans } from 'next/font/google';

import Layout from '../src/components/templates/Layout';
import '../src/assets/css/style.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icons: [
    {
      rel: 'icon',
      type: 'image/x-icon',
      url: '/favicon-dark.ico',
    },
    {
      rel: 'icon',
      type: 'image/png',
      url: '/icon-192-dark.png',
    },
    {
      rel: 'apple-touch-icon-precomposed',
      url: '/apple-touch-icon-dark.png',
    },
  ],
};
// const montserrat = Montserrat({
//   weight: ['500', '600', '700'],
//   style: ['normal', 'italic'],
//   subsets: ['latin'],
//   display: 'swap',
//   variable: 'Montserrat, sans-serif',
// });
// const open_sans = Open_Sans({
//   weight: ['400', '500', '600', '700'],
//   style: ['normal', 'italic'],
//   subsets: ['latin'],
//   display: 'swap',
//   variable: 'Montserrat, sans-serif',
// });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: pt.node,
};
